### ISSUE TITLE
Main cannot be found

### ISSUE THREAD

**Issue by saimouli** [watson-developer-cloud/java-sdk#321]
I'm using eclipse mars
![capture](https://cloud.githubusercontent.com/assets/14081959/15879898/2fef2830-2cf6-11e6-8809-3d88d882c121.JPG)

![capture2](https://cloud.githubusercontent.com/assets/14081959/15879911/52c433b4-2cf6-11e6-8336-b0c9289d2f9c.JPG)

What would be the main class, if I want to run visual recognition service?

**Comment by GrapeBaBa** [comment]
@saimouli It seems you don't make examples catelog as source code catelog.

**Comment by max-vogler** [comment]
Hey @saimouli. You have already found the right class: `examples/com/ibm/watson/developer_cloud/visual_recognition/v2/VisualRecognitionExample.java`

You have to move it into the `src` folder to execute it, because `examples` is not part of your build path:
`src/com/ibm/watson/developer_cloud/visual_recognition/v2/VisualRecognitionExample.java`

**Comment by germanattanasio** [comment]
![me2](http://g.recordit.co/7wAYHRPnkf.gif)

**Comment by germanattanasio** [comment]
I'm closing this since it's not a problem in the SDK. We don't want to make the examples to be part of the classpath.
