### ISSUE TITLE
[personality-insights] Consider changing names of content-type methods for consistency

### ISSUE THREAD

**Issue by jeffpk62** [watson-developer-cloud/java-sdk#339]
The ContentItem class includes a contentType() method to set the content type of an item.  But the getter and setter for the attribute are named getContenttype() and setContenttype().  It would probably be more consistent for the class and more parallel with other methods of the SDK if these methods were named getContentType() and setContentType().

**Comment by jeffpk62** [comment]
Alternatively, you could also change the contentType() method to contenttype().  Either approach would probably be fine.

**Comment by GrapeBaBa** [comment]
@jeffpk62  Your suggestion is good, but as these two methods are public, change the signature will break the user if they upgrade.
@germanattanasio Thoughts?

**Comment by germanattanasio** [comment]
We can deprecate the existing method and add the new ones

**Comment by jeffpk62** [comment]
Yeah, I was aware of breaking the public signatures, Kai.  It's obviously not a critical change, I really just wanted to point it out for your consideration.  It's really up to you guys to decide whether it's worth the change.  I appreciate the quick consideration.

**Comment by max-vogler** [comment]
This class contains some more fields that are not capitalized (`parentid`, `sourceid`, `userid`) and generally mixes the *Builder* and *Model* pattern because it exposes methods like `charset(String) -> ContentItem` and `setCharset(String) -> void`. 

I would suggest:

1. Deprecating all Builder-style setters: `charset(String), content(String), contentType(String), created(Date), forward(Date), language(String), parentid(String), reply(boolean), sourceid(String), updated(Date), userid(String)`
2. Deprecating getters and setters with missing capitalization: `getcontenttype(), setcontenttype(String), getParentid(), setParentid(String), getUserid(), setUserid(String), getSourceid(), setSourceid(String)`
3. Add getters and setters with correct capitalization: `getContentType(), setContentType(String), getParentId(), setParentId(String), getUserId(), setUserId(String), getSouceId(), setSourceId(String)`

I understand that these are a lot of changes though. Any ideas?

**Comment by GrapeBaBa** [comment]
@max-vogler Sounds good.

**Comment by GrapeBaBa** [comment]
@germanattanasio @max-vogler Let me fix this one.

**Comment by germanattanasio** [comment]
It's all yours @GrapeBaBa
