### ISSUE TITLE
Cannot resolve symbol "LanguageTranslator"

### ISSUE THREAD

**Issue by ysfAskri** [watson-developer-cloud/java-sdk#372]
Cannot resolve symbol **"LanguageTranslator"** even i put the Maven dependency in  .pom file.
The Java compiler succeeded to recognize **"TranslationResult"** but **"LanguageTranslator"** he's couldn't.

[ScreenShot](http://hpics.li/a78332d)

**Comment by max-vogler** [comment]
Hi @ysfAskri: You're getting this error because we renamed `LanguageTranslation` to `LanguageTranslator`, which is already in the README file, but not yet in the Maven release.

To fix your bug use `LanguageTranslation` from the package `com.ibm.watson.developer_cloud.language_translation.v2.LanguageTranslation` like this:

```java
LanguageTranslation service = new LanguageTranslation();
```

**Comment by ysfAskri** [comment]
Thnx you

regards
