### ISSUE TITLE
Move the android-sdk as a module of this project and switch from maven to gradle

### ISSUE THREAD

**Issue by germanattanasio** [watson-developer-cloud/java-sdk#478]
We want to have the android-sdk as part of this repository so that the releases are seamless. Since the android-sdk is using Gradle we need to either move this repo to use Gradle or find a workaround to call Gradle from Maven.

Let's start with https://gradle.org/maven_vs_gradle/

**Comment by germanattanasio** [comment]
See https://zeroturnaround.com/rebellabs/java-build-tools-part-2-a-decision-makers-comparison-of-maven-gradle-and-ant-ivy/

**Comment by kane77** [comment]
I have started to make gradle build work. I have a question. Why is there a separate module for tests? IMHO it would be better to have tests as part of module. I would also split the unit tests from integration tests (src/main, src/test and src/it) as this works nicely in gradle. What do you think?

**Comment by blakesteve** [comment]
Hi @kane77 

How far along are you on this process? Just curious because I began work on this yesterday and don’t want to duplicate effort.

I agree about splitting unit and integration tests – but which module do you intend the tests to be a part of? It doesn’t make much sense to me for tests to be under a single module. Why would you be testing parts of one module from within an unrelated module? I don’t really see the value in changing the structure and potentially making it more difficult for visitors to the repo to find the tests.

**Comment by kane77** [comment]
hi @blakesteve 
it's building all the projects, running checkstyle and running tests so far, there is still couple of things missing (maven release, animal sniffer, coberture etc.).
What I meant was instead of tests residing in special module to have them as part of the module - tests for 'language-translation' service would be found under 'language-translation' module.
This way it would be possible to build each module separately including tests and integration tests.

**Comment by germanattanasio** [comment]
@kane77 tests are in one module because we need to have the credentials for the services and they change frequently. I don't want to be dealing with multiple credentials files. What do you suggest for that?

**Comment by kane77** [comment]
@germanattanasio the credentials could be part of core module's test resources and core module would be dependency for all other modules.

**Comment by germanattanasio** [comment]
What about tests that are using more than one module like [this](https://github.com/watson-developer-cloud/java-sdk/blob/master/tests/src/test/java/com/ibm/watson/developer_cloud/service/GenericServiceTest.java)

**Comment by blakesteve** [comment]
@kane77 I'm just curious on the status of modularization of the android sdk?

I'm wondering if we should create a separate issue for the discussion on tests to move forward with the merging of the sdks. Thoughts?

**Comment by kane77** [comment]
@germanattanasio yes, that is true that currently there is this test that requires all services. What I would suggest to split it into generic test and each service would then call checkApiKey in it's own test. What do you think? I've created a build script that leaves the structure as is.
@blakesteve I'll create pull request, but this only deals with making gradle build work. There will have to be some testing by someone that has access to travis  to make sure it works correctly.

**Comment by kane77** [comment]
I've set up gradle branch. This branch is now built using gradle. There will still be some changes, but I can now start integrating android-sdk.

**Comment by germanattanasio** [comment]
@kane77 I'm playing around with the branch and everything looks good. I have a few questions before merging the branch.

1. How can I do a release to maven central? I'm looking at [this plugin](https://docs.gradle.org/current/userguide/publishing_maven.html), but I didn't find a way on how to integrate it yet. Do you know of another project using gradle and doing releases to Maven central?

2. How can I generate the `java-sdk-3.5.1-jar-with-dependencies.jar` along with `java-sdk-3.5.1.jar` when I run `gradle build'?


@blakesteve feel free to answer if you know the questions above.

**Comment by blakesteve** [comment]
I have picked up on this since it's been inactive for awhile, aiming to complete by end of sprint. Running into some strange issues building with multiple gradle projects.

I am unsure about the first question, but I believe there is a simple flag you can add to your gradle build to build with dependencies. alternatively you can create a gradle task in your `build.gradle` that compiles dependencies and then run `gradle [task]` e.g. https://www.mkyong.com/gradle/gradle-create-a-jar-file-with-dependencies/

Perhaps @Hsaylor can help with 1.

**Comment by kane77** [comment]
Hi @germanattanasio 
I've been away for a while. Here are the answers:
1. there is a task called uploadArchives, that does just that.. It uploads to snapshot repository in case the version ends with '-SNAPSHOT' and to release repository (http://oss.sonatype.org/service/local/staging/deploy/maven2/) if it isn't snapshot version. I haven't been able to test this, but it should work..
2. I will create a task to create 'fat jar'.
