### ISSUE TITLE
[speech-to-text] HTTP - large set of keywords results in a error

### ISSUE THREAD

**Issue by amaresh-rajasekharan** [watson-developer-cloud/java-sdk#822]
I am using HTTP Session based request to process multiple audio recordings through STT service.

I also use keyword lookup and set the keyword threshold. When I have large number of key words the request throws an error like the following:

Starts with "INFO: <-- 400 Bad Request"
Prints the whole request with all the parameters and the keywords, followed by the message
length exceeds the maximum length 1024
at com.ibm.watson.developer_cloud.service.WatsonService.processServiceCall(WatsonService.java:408)
at com.ibm.watson.developer_cloud.service.WatsonService$1.execute(WatsonService.java:174)

I am using JDK 1.8. The problem goes away if I reduce the number of keywords I am looking up. 
But this problem is present only when I do a session oriented request by setting the session in the RecognizeOptions.  The error does not arise otherwise (when I don't set the session).

**Comment by mkistler** [comment]
The `recognize` method in the Java SDK uses the form of the `recognize` API that passes keywords as query parameters -- that is, as part of the URL.  All services impose limits on the length of the URL -- it seems that for STT this limit is 1024.

I strongly suspect that this issue is _not_ limited to the session-based form of the API, since the sessionless also passes keywords in the query string, it _will_ fail if given enough keywords.

There are other forms of the `recognize` API that pass keywords in the body of the request (as formData), and this would allow _very large_ keyword sets to be passed, but these are not used in the Java SDK.

**Comment by jeffpk62** [comment]
See this section of the documentation:  https://console.stage1.bluemix.net/docs/services/speech-to-text/http.html#HTTP-multi.  It includes the following information:

The multipart approach is intended for two use cases:

- For use with browsers for which JavaScript is disabled. Multipart requests based on form data do not require the use of JavaScript.
- When the parameters used with the recognition request are greater than the 8 KB limit imposed by most HTTP servers and proxies. This can occur, for example, if you want to spot a very large number of keywords. Passing the parameters as form data avoids this limit.

**Comment by lpatino10** [comment]
Closing this issue as a solution was identified.
